### ISSUE TITLE
Win 7 compability with 3.0.3.0

### ISSUE THREAD

**Issue by Vahsify** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#105]
In Windows 7, when you start the game with the version 3.0.3.0, screen resolutions other than the standard ones for Diablo II do not work.

Tested on 2 PCs with Widows 7, 2 Windows 10 and 1 Windows 11. In Windows 10 and 11 all works fine.

**Comment by IAmTrial** [comment]
Could you provide additional information about the Windows 7 machine? Is Visual C++ 2022 redistributable installed? What resolutions are configured in the JSON file? What version of Diablo II is running? How is the DLL being loaded into the game?

**Comment by Vahsify** [comment]
1. Visual C++ 2022 redistributable installed.
2. 640x480, 800x600, 1068x600.
3. 1.09d.
4. dll is loaded via D2DX.

On the windows 10 version, 1068x600 is present in the d2dx_log.txt file, but not on Windows 7.

SGD2FreeRes version 3.0.2.6d works correctly on Windows 7. 

Except "Fix a New Stats and New Skill button 800x600 alignment issue in 1.09D after using a waypoint." Which has been corrected in the version 3.0.3.0.

**Comment by IAmTrial** [comment]
I can confirm that the bug is happening in my test machine. I will look into it.

**Comment by IAmTrial** [comment]
Caused by commit [68f9d5502512961ec270588ec1d044eed172ee46](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/commit/68f9d5502512961ec270588ec1d044eed172ee46). Disabling the newly added code allows Windows 7 to load the library correctly.

**Comment by IAmTrial** [comment]
Fixed for 3.0.1.1.
