### ISSUE TITLE
Game crash when minimizing (screenshots)

### ISSUE THREAD

**Issue by Nicks182** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#117]
I'm using the QoL mod pack which includes the FreeRes mod and the crash I'm getting looks to be FreeRes relates based on the error message.

Link to QoL: https://github.com/whipowill/d2-plugy-qol

For about a week the game has been running fine, but since yesterday the game would crash every time I switch focus and it minimizes. I have things setup in such a way that drivers ect do not update automatically, but I did get a Win10 update.

That said, it's not consistent. Last night it ran perfectly fine with zero crashes. Today it's crashing again. Below are 2 screenshots of the 2 messages that comes up, but I unfortunately don't know what this really means or what I could do to try and solve it.

I just restarted my PC and now I have no crashing... for now...

![2023-02-17 13_54_07-Window](https://user-images.githubusercontent.com/13113785/219866193-db4d5882-210f-4903-954b-59f63f1477d2.png)

![2023-02-17 13_54_15-Window](https://user-images.githubusercontent.com/13113785/219866201-ffb215c7-4cb7-4af9-ba90-1e623b72368d.png)

**Comment by IAmTrial** [comment]
That version of D2DX uses an outdated version of SGD2FreeRes, at least 2 years old. Use a modern version of SGD2FreeRes and use something like https://github.com/eleriaqueen/d2dx.

**Comment by Nicks182** [comment]
Thanks for the feedback. Will look into it. Chrz
