### ISSUE TITLE
SGD2FreeResolution and D2GL

### ISSUE THREAD

**Issue by RestDreams** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#123]
SGD2FreeResolution does not support widescreen mode in D2GL. 
It just doesn't work.  Link to my request on the D2gl page
[https://github.com/bayaraa/d2gl/issues/61](https://github.com/bayaraa/d2gl/issues/61)

**Comment by IAmTrial** [comment]
I've edited your message to link to the correct link, I'll take a look.

**Comment by IAmTrial** [comment]
What version of SGD2FreeRes.dll were you using at the time?

**Comment by RestDreams** [comment]
Widescreen mode does not work on latest SGD2FreeRes.dll 3.0.4.0 and latest D2GL 1.1.2.
Widescreen mode worked on D2GL 1.1.1, which included a custom build of SGD2FreeRes.

**Comment by RestDreams** [comment]
I have added the resolution in SGD2FreeResolution.json file. Everything works well. Apparently I'm dumb, it's not obvious that the "json" file format is opened by a text editor. But it worked out in the end, thanks.
