### ISSUE TITLE
compile error with master branch 

### ISSUE THREAD

**Issue by buuug7** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#129]
![image](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/assets/12119289/0b557a20-e054-4713-b2e9-631940a52c92)

i install nasm from `https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/` and comiple with this error accurd, someone can help me which config need to fix for this error?

![image](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/assets/12119289/67679634-6d6e-4dab-9ba5-67c53aeaee84)

**Comment by IAmTrial** [comment]
The compile error is because you are attempting to compile the source code using x64-Debug, when you need to change the configuration to x86.

**Comment by buuug7** [comment]
@IAmTrial thanks , it works for me ,  i closed the issue
