### ISSUE TITLE
Support center Life/Mana Orb in high-definition

### ISSUE THREAD

**Issue by qwertyue** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#140]
just like this

![image](https://github.com/user-attachments/assets/26cb7278-4cc3-4629-8ef9-b4449977de6d)

**Comment by nelsonmenon** [comment]
this is already set as an enhancement in issue #11

**Comment by qwertyue** [comment]
> this is already set as an enhancement in issue #11

 thank you for your explanation, it's a good news.

**Comment by IAmTrial** [comment]
Duplicate of #11 .

**Comment by qwertyue** [comment]
> Duplicate of #11 .

When is it scheduled to be released？

**Comment by IAmTrial** [comment]
> When is it scheduled to be released？

There is no exact deadline, but it is on the radar.
