### ISSUE TITLE
Integration with D2DX Glide wrapper

### ISSUE THREAD

**Issue by bolrog** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#21]
I'm working on a new Glide wrapper for Diablo 2 (https://www.github.com/bolrog/d2dx), and a big part of my focus is compatibility with existing and upcoming game mods. As such, it would be really nice to get this project working with it. Would you be interested in collaborating?

Reading through the code, it occurs to me that a nicer integration than writing raw dwords at some offset would be if I export some function. E.g. one that will override the resolution set by the next call to grSstWinOpen.

**Comment by IAmTrial** [comment]
I would be interested in collaborating! It would definitely be easier to work with than directly patching the wrapper, as I have done with other Glide wrappers.

**Comment by bolrog** [comment]
Excellent! As a starting point, I've made a proposed configurator API here: https://github.com/bolrog/d2dx/blob/6d76b7f6cb1c4a7941c965780c6ae0f1743e7730/src/d2dx/D2DXConfigurator.h

It is what I currently use for the "built-in" version of SD-HD that I'm including with D2DX, but I'm open for any opinions and suggestions.

**Comment by IAmTrial** [comment]
Thanks a lot! I will integrate this external API via GetProcAddress and plan to support D2DX before the next release.

**Comment by IAmTrial** [comment]
The current versions of D2DX come with SGD2FreeResolution and appear to be compatible. This issue can therefore be closed.
