### ISSUE TITLE
Some Glide3x.dll not working using current version v3.0.2.0

### ISSUE THREAD

**Issue by MAXBURAOT** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#38]
Ive test the ff:
Using DIablo II v1.14d with SlashGaming-Diablo-II-Free-Resolution v3.0.2.0

Glide3x.dll nGlide ~>BlackScreen
Glide3x.dll D2DX ~> Working
Glide3x.dll Sven's (v1.4.4.21) ~> Working on D2v1.13d / Not Working for D2v1.14d (Game not launching)
                                              ~> but launching on a normal -w -3dfx (D2v1.14d) without freeres
                                              
Heres my settings

```
@echo off
set "CURRENT=%~dp0"

START "" "%CURRENT%SGGL.exe" ^
    	-g "%CURRENT%Game.exe" ^
    	-a "-w -3dfx" ^
	-n 1 ^
	-l "%CURRENT%SGD2FreeDeMin.dll" ^
	-l "%CURRENT%SGD2FreeDisplayFix.dll" ^
	-l "%CURRENT%SGD2FreeMultibox.dll" ^
	-l "%CURRENT%SGD2FreeRes.dll" ^
	-l "%CURRENT%SGD2TrueVersionLabel.dll" ^
```

![4](https://user-images.githubusercontent.com/33173384/117008160-02595d80-ad1d-11eb-8b17-d55f121474c5.png)
![5](https://user-images.githubusercontent.com/33173384/117008474-5a905f80-ad1d-11eb-8893-e804a31cbcbd.png)
![2](https://user-images.githubusercontent.com/33173384/117012903-f6bc6580-ad21-11eb-9c5c-59516fabda86.png)

**Comment by iamyoyz** [comment]
@MAXBURAOT can I ask what parameter settings you use on D2Dx? I tried to work but mouse was stuck in the left screen I've also encounter the same problem as yours in other glides but also having problems in in D2DX on 1.14d

**Comment by IAmTrial** [comment]
At the moment, SGGL for injecting SGD2FreeRes into Glide mode will not always work. Based on my observations, using PlugY to load the library in Glide mode will work.

For a technical reason why SGGL doesn't work, it likely has to do with the state of the Diablo II program when SGD2FreeRes is loaded. SGGL loads the DLL immediately after the process is created. PlugY likely loads SGD2FreeRes later in the program, after some initialization is completed.

As for fixing this issue, there isn't really anything I would want to change in SGD2FreeRes to resolve this issue. I will likely come up with a solution for this problem some time in the future, in another repository.

**Comment by borgdin** [comment]
I had the same or even worse problem with PlugY 14.02 (testing base : diablo2 expansion 1.14d). 
PlugY didn't load SGD2FreeRes.dll to launch the game, even though "DllToLoad=SGD2FreeRes.dll" is set in PlugY.ini. 
The only thing that works is D2DX glide3x.dll, but max resolution in game is capped at 920x548, and you can't change it by editing D2DX_SGD2FreeResolution.cfg.

**Comment by borgdin** [comment]
A few further testing results with the latest PlugY and Sven's glide wrapper....
For D2 1.13c/d: it works fine. SGD2FreeRes.dll loading successful. 
For D2 1.14d: loading failure. Game can't be launched.

**Comment by master861** [comment]
hmm in 1.13d dont works for me and i tryed svens and even balrogs gliede dont work for me

**Comment by oGkspAz** [comment]
> The only thing that works is D2DX glide3x.dll, but max resolution in game is capped at 920x548, and you can't change it higher by editing D2DX_SGD2FreeResolution.cfg.
D2DX gets it's settings from copying / renaming d2dx-defaults.cfg to d2dx.cfg and changing settings in that instead.

**Comment by IAmTrial** [comment]
This issue is long outdated.  Anyone still facing this issue should create a new issue.
