### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by bolrog** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#40]
I am not sure how much this one is dependent on the mods used, but here are the specs:

LoD 1.14d
PlugY 14.02

Details follow, I tried to capture a bit of callstack etc.
I find it weird that it jumps to 0x0020006C, it feels more like some value than a pointer (and the debugger shows ??'s at that addr).

"Exception thrown at 0x0020006C in Game.exe: 0xC0000005: Access violation executing location 0x0020006C."

func_ptr = 0x00601840
num_params = 0x00000001

![image](https://user-images.githubusercontent.com/81111887/119032817-e6a4b700-b9ac-11eb-8068-484aad9aad0e.png)

![image](https://user-images.githubusercontent.com/81111887/119032697-c4129e00-b9ac-11eb-8f6c-e65b02e84f04.png)

![image](https://user-images.githubusercontent.com/81111887/119032747-d1c82380-b9ac-11eb-95d8-fd5edce102b4.png)

![image](https://user-images.githubusercontent.com/81111887/119033139-2a97bc00-b9ad-11eb-894f-b94fe71d1db1.png)

**Comment by IAmTrial** [comment]
Jumping to 0x0020006C is indeed not intended behavior. The function should be calling a function located at 0x00601840 (which is Game.exe base + 0x201840). The `func_ptr` appears to be the correct value, so it doesn't seem to be crashing due to incorrect parameters.

I will try to replicate the issue with the files you have sent.

**Comment by IAmTrial** [comment]
I just tested the crash by following your instructions and was able to crash the game on a PlugY game without SGD2FreeRes loaded.

**Comment by bolrog** [comment]
Oops. So it's a PlugY bug... sorry. :) I'll see if I can chase down the author of that.
