### ISSUE TITLE
D2SE Compatibility

### ISSUE THREAD

**Issue by XPZ2k15** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#41]
How would one install onto D2SE? It said that there is D2SE compatibility.  Can you provide any instructions?

**Comment by IAmTrial** [comment]
I used D2SE's built-in PlugY to load the game, but there might be other ways via config.

**Comment by Gecko94** [comment]
I reported this in another one of your projects today.

I've tried all kinds of ways to get SGD2FreeRes working in D2GS. Here are a few methods and these are the errors I get.


**1) Load from PlugY.ini**
![Error_LaunchedFromD2SEPlugY14](https://user-images.githubusercontent.com/85077147/120117335-f90bb700-c149-11eb-9a38-fc78425e4c7b.jpg)

Version string in D2SE_Setup.ini
D2Core=1.13c


**2) Load from D2SE_Setup.ini**
ModAllowPlugY=1
ModDll2=SGD2FreeRes.dll

Tried loading with and without ModMPQ3=SGD2FreeRes.mpq
no config file generated - no error on screen


**3) Rename SGD2FreeRes.dll to PlugY.dll to load it that way..**
![Error_LaunchedFromD2SERenamedToPlug_dll](https://user-images.githubusercontent.com/85077147/120117429-6fa8b480-c14a-11eb-856d-01c66ad1e372.jpg)

**Comment by IAmTrial** [comment]
Closing this issue because the user solved their issue on Discord.
![image](https://user-images.githubusercontent.com/26683324/120265469-01044d80-c255-11eb-9560-8956ccaf7a5d.png)
