### ISSUE TITLE
Diablo II Resurgence whitelisting not working as described

### ISSUE THREAD

**Issue by esbe1175** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#71]
Currently SGD2FreeRes on D2 Resurgence servers only allow 640x480 & 800x600 instead of the intended full range (640x480, 800x600, 856x480, 1068x600).

I spoke briefly with the developer & owner of the resurgence private server, he told me he wanted and had been trying to get D2DX working (Which uses SGD2FreeRes as its resolution scaling). So, it seems like he's still fine with it. He's a busy guy so I don't know when he'll get around to hitting you up about fixing the available resolutions, so I thought I'd shoot you a request here and see what you think :).

**Comment by IAmTrial** [comment]
I can confirm that the bug is occurring as you described. It would appear that the server had changed IPs, which resulted in the server not being detected by SGD2FreeRes. I will release a fix for this that should alleviate this problem, for as long as the server does not suddenly change IPs.

**Comment by esbe1175** [comment]
Awesome, thank you!

**Comment by IAmTrial** [comment]
Resolved by #75. Is now a part of the newest release, 3.0.2.3.
