### ISSUE TITLE
Trying to update SGD2FreeRes in Bolrogs/D2DX gives me errors.

### ISSUE THREAD

**Issue by jaydee2k** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#82]
Hi,

sadly it looks like Bolrog abandoned his awesome glide wrapper which led me to try to update
your built in SGD2FreeRes by myself because of the 1.09d cut-scene transition bug.
Built in FreeRes in Bolrogs repo is still 3.0.2.0. I tried to include 3.0.2.1 in changing the needes files
from your release. Then compressed these files with pocketlzma like Bolrog did and compiled his source
with Visual Studio. Everything worked to this point. Whenever I try to launch a char now ingame this error occurs.
![Screenshot 2022-05-20 090009](https://user-images.githubusercontent.com/38560548/169478414-1da722a9-a231-4a4e-824d-b661e2f39b12.png)

Since I'm no expert it would be super kind if you could help me out with this or have any idea what is needed to make it working.

Thanks in advance !

**Comment by esbe1175** [comment]
Yo, looks like you are compiling using the Modders version of sgd2freeres

You can make your current compiled dll work by having -direct in your launch arguments and extracting the "data" folder of the Modder's version to the diablo II root diretory. Same can be accomplished by adding the data folder to the Patch_D2.mpq.

The real way would be to compile a version using the "vanilla" version, so it includes the files properly. Gl.

**Comment by jaydee2k** [comment]
Nono I use the vanilla version just like Bolrog did. 
SGD2FreeRes.dll
SGD2FreeRes.mpq
These files are compressed with .lzma and then built into glide3x.dll.
Everything is working including the autoextract of these files into the main D2 directory on every startup.
But then this error occurs. Even when I extract the the data from the mpq with -direct -txt etc... the error goes away
but then there are only 640x480 & 800x600 ingame. Must be somethin in Bolrogs source code then which needs to be tweaked...

**Comment by IAmTrial** [comment]
I'm not sure if this is directly related to SGD2FreeRes. Will be closing this issue in a week if there is no further response.
